### ISSUE TITLE
getting AttributeError: 'function' object has no attribute 'commit_select' in a Flask-Admin Peewee web app

### ISSUE THREAD

**Issue by gerosalesc** [mrjoes/flask-admin#23]
Following [this example](https://github.com/flask-admin/flask-admin/blob/master/examples/peewee/app.py) I integrated Flask admin with some already created peewee models. Everything looks great until I try the list view of the admin interface, but first some context:

<h2>The Code</h2>

The important part of the **app.py** file:

```
@inject.params(db=Database)
def create_app(config_object=DevConfig, db=None):
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    admin = Admin(app, name=__name__, template_mode='bootstrap3')
    __add_admin_views(admin)
    return None


def __add_admin_views(admin):
    admin.add_view(ClientAdmin(entities.Client))
    return None
```

<h2>The Error</h2>

This happens when I try to request the list of clients (http://127.0.0.1:5000/admin/client/):

```
Traceback (most recent call last):
  File "MY_ENV_PATH/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "MY_ENV_PATH/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "MY_ENV_PATH/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "MY_ENV_PATH/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "MY_ENV_PATH/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "MY_ENV_PATH/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "MY_ENV_PATH/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "MY_ENV_PATH/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 1738, in index_view
    view_args.search, view_args.filters)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 353, in get_list
    query = self.get_query()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 328, in get_query
    return self.model.select()
  File "MY_ENV_PATH/lib/python2.7/site-packages/peewee.py", line 4458, in select
    query = SelectQuery(cls, *selection)
  File "MY_ENV_PATH/lib/python2.7/site-packages/peewee.py", line 2696, in __init__
    self.require_commit = self.database.commit_select
AttributeError: 'function' object has no attribute 'commit_select'
```

As seen in [SO](http://stackoverflow.com/questions/35140925/getting-attributeerror-function-object-has-no-attribute-commit-select-in-a)

**Comment by mrjoes** [comment]
If you try our example - does it work?

So far it looks like Peewee problem - Flask-Admin does `self.model.select()` to start a query and then it crashes somewhere inside of Peewee.

**Comment by gerosalesc** [comment]
Will try the example alone, maybe it's a version problem or something

**Comment by gerosalesc** [comment]
Ok @mrjoes first thanks for the suggestion. I tried the example as plain as Copy pasting it and I am getting this error:

```
MY_ENV_PATH/bin/python "MY_PROJECT/bgadmin/app.py"
Traceback (most recent call last):
  File "MY_PROJECT/bgadmin/app.py", line 88, in <module>
    admin.add_view(UserAdmin(User))
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 170, in __init__
    menu_icon_value=menu_icon_value)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 718, in __init__
    self._refresh_cache()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 810, in _refresh_cache
    self._refresh_forms_cache()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 735, in _refresh_forms_cache
    self._create_form_class = self.get_create_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 1147, in get_create_form
    return self.get_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/model/base.py", line 1100, in get_form
    return self.scaffold_form()
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 264, in scaffold_form
    form_class = self.scaffold_inline_form_models(form_class)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/view.py", line 297, in scaffold_inline_form_models
    m)
  File "MY_ENV_PATH/lib/python2.7/site-packages/flask_admin/contrib/peewee/form.py", line 213, in contribute
    for field in info.model._meta.get_fields():
AttributeError: 'ModelOptions' object has no attribute 'get_fields'
```

The version of the libraries are: Flask 0.10.1, Flask-Admin 1.4.0, peewee 2.8.0

Thanks in advance.

**Comment by gerosalesc** [comment]
It seems the last problem is due to a compatibility issue with the latest versions of peewee as described in [#1117](https://github.com/flask-admin/flask-admin/issues/1117) and [#1125](https://github.com/flask-admin/flask-admin/pull/1125) , will try the suggested solution to see if it solve my original problem too

**Comment by gerosalesc** [comment]
@mrjoes I am moving this to the current project [here](https://github.com/flask-admin/flask-admin/issues/1185). Apologies for the confusion.
