### ISSUE TITLE
use Flask-Admin 1.0.9 with UnicodeDecodeError but Flask-admin 1.0.8 is OK?

### ISSUE THREAD

**Issue by shnode** [mrjoes/flask-admin#781]
reproduce the error like this:

    Traceback (most recent call last):
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
        return self._run_view(f, *args, **kwargs)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_admin/base.py", line 344, in _run_view
        return fn(self, *args, **kwargs)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_admin/base.py", line 410, in index
        return self.render(self._template)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_admin/base.py", line 284, in render
        return render_template(template, **kwargs)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
        context, ctx.app)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
        rv = template.render(context)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
        return self.environment.handle_exception(exc_info, True)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_admin/templates/bootstrap2/admin/index.html", line 1, in top-level template code
        {% extends 'admin/master.html' %}
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_admin/templates/bootstrap2/admin/master.html", line 1, in top-level template code
        {% extends admin_base_template %}
      File "/Users/melodic/private/duskfall/app/templates/layout.html", line 2, in top-level template code
        {% extends 'admin/base.html' %}
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 6, in top-level template code
        <title>{% block title %}{% if admin_view.category %}{{ admin_view.category }} - {% endif %}{{ admin_view.name }} - {{ admin_view.admin.name }}{% endblock %}</title>
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 6, in block "title"
        <title>{% block title %}{% if admin_view.category %}{{ admin_view.category }} - {% endif %}{{ admin_view.name }} - {{ admin_view.admin.name }}{% endblock %}</title>
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/speaklater.py", line 136, in __unicode__
        return unicode(self.value)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/speaklater.py", line 115, in <lambda>
        value = property(lambda x: x._func(*x._args, **x._kwargs))
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_babelex/__init__.py", line 533, in gettext
        t = self.get_translations()
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/flask_babelex/__init__.py", line 519, in get_translations
        domain=self.domain)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/babel/support.py", line 546, in load
        return cls(fp=fp, domain=domain)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/babel/support.py", line 519, in __init__
        super(Translations, self).__init__(fp=fp)
      File "/Users/melodic/.virtualenvs/self-flask/lib/python2.7/site-packages/babel/support.py", line 283, in __init__
        super(NullTranslations, self).__init__(fp=fp)
      File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 180, in __init__
        self._parse(fp)
      File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gettext.py", line 337, in _parse
        tmsg = unicode(tmsg, self._charset)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xad in position 0: invalid start byte

I also use Flask -Babel . Wonder if something wrong with Flask Babel??Before translate something , Flask-Admin 1.0.9 alse works.

**Comment by lanybass** [comment]
buddy upstairs, give me five~ we are in the same boat.
```
  File "/home/vagrant/.pyenv/versions/flask/lib/python2.7/site-packages/flask_admin/templates/bootstrap2/admin/model/list.html", line 16, in block "model_menu_bar"
    <a href="javascript:void(0)">{{ _gettext('List') }} ({{ count }})</a>
  File "/home/vagrant/.pyenv/versions/flask/lib/python2.7/site-packages/flask_babelex/__init__.py", line 533, in gettext
    t = self.get_translations()
  File "/home/vagrant/.pyenv/versions/flask/lib/python2.7/site-packages/flask_babelex/__init__.py", line 519, in get_translations
    domain=self.domain)
  File "/home/vagrant/.pyenv/versions/flask/lib/python2.7/site-packages/babel/support.py", line 546, in load
    return cls(fp=fp, domain=domain)
  File "/home/vagrant/.pyenv/versions/flask/lib/python2.7/site-packages/babel/support.py", line 519, in __init__
    super(Translations, self).__init__(fp=fp)
  File "/home/vagrant/.pyenv/versions/flask/lib/python2.7/site-packages/babel/support.py", line 283, in __init__
    super(NullTranslations, self).__init__(fp=fp)
  File "/home/vagrant/.pyenv/versions/2.7.8/lib/python2.7/gettext.py", line 180, in __init__
    self._parse(fp)
  File "/home/vagrant/.pyenv/versions/2.7.8/lib/python2.7/gettext.py", line 337, in _parse
    tmsg = unicode(tmsg, self._charset)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xad in position 0: invalid start byte
```
can't call _gettext(xxx) with out error. 
Error in 1.0.9 . But downgrade to 1.0.8 ok.

**Comment by pawl** [comment]
Is it happening with a specific language and endpoint?

I went to "/model1/?language=fr" in this example and didn't see any issues: https://gist.github.com/pawl/1b422e8ca5349fea3645

**Comment by shnode** [comment]
### about Flask-Babel

I've tried to use 'zh_Hans_CN' or 'zh_CN' to translate my project into Chinese，but they didn't work anyway, though they all in my system's locale. Finally I found that only `zh` works for me:

    @babel.localeselector
    def get_locale():
        return 'zh'

 otherwise the translations won't take effect, they will remain English.

### about Flask-Amin

I've never used any other language in url-endpoint. 

And it has good behavior in Flask-Admin 1.0.8 . So I thought maybe this only happened in Chinese?

**Comment by pawl** [comment]
Chinese should be fixed in the current master branch with this pull request: https://github.com/mrjoes/flask-admin/pull/754

If you can reproduce the UnicodeDecodeError issue in a gist, i'll help fix it.

**Comment by lanybass** [comment]
@pawl if you have any IM(GTalk or other), I'll show you the error online and you can debug

**Comment by shnode** [comment]
@pawl 
This is a simple reproduce bug gist:  [go to gist](https://gist.github.com/shnode/5e41e6f7fc1a28946dd2)

the `messages.po`s generation all follows the document.

and in Flask-Admin 1.0.8, it can successfully check the admin page without a hinch.

but in Flask-Admin 1.0.8, it gives me a `UnicodeDecodeError` like this issue above.

**Comment by lanybass** [comment]
@shnode 你的问题是babel的版本问题吧，和我们不是一个问题啊。怎么也会有UnicodeDecodeError？

**Comment by shnode** [comment]
It's my fault for this issue.`zh_Hans_CN' takes effect in Flask-Admin 1.0.9. 

But another two question exist.

 - Flask-Admin don't translate himself such as `Home` etc. whatever I change the `BABEL_DEFAULT_LOCALE` in config.py is useless.

 - Flask-Admin filter still conflict with babel, which shows me a Error like:

    TypeError
    TypeError: key lu'\u521b\u5efa\u65f6\u95f4' is not a string

I will start a new issue for the questions above.

**Comment by baocaixiong** [comment]
我也出现同样地问题
