### ISSUE TITLE
Support custom SQLAlchemy types for filters

### ISSUE THREAD

**Issue by jmagnusson** [mrjoes/flask-admin#804]
I have a special case where I've used `sqlalchemy.types.Text` for all string/text columns (as PostgreSQL doesn't have any reduced performance from it and gives you limitless length on the input).

I'm trying to make a general solution where I use my own custom SQLAlchemy type like this:

```python
from .sqla import types


class ShortText(types.TypeDecorator):
    impl = types.Text

...

class MyDeclarativeModel(Base):
    my_attr = Column(ShortText)
```

However when I try to use it in my Flask-Admin view like this:

```python
from flask.ext.admin.contrib.geoa import ModelView

class MyView(ModelView):
    column_filters = ('name', )
```

I get the following error:

`Exception: Unsupported filter type my_attr`

Shouldn't this work considering it's based on the same implementation?

**Comment by jmagnusson** [comment]
The issue I was having was caused by #806. Supporting custom types does work and is done by creating a custom `flask_admin.contrib.sqla.filters.FilterConverter`

**Comment by alex1007** [comment]
```
Traceback (most recent call last):
  File "manage.py", line 39, in <module>
    app = create_app(os.getenv('CONF_CONFIG') or 'default')
  File "/Users/leonf/Develop/workspace/xxx/app/__init__.py", line 101, in create_app
    endpoint='admin_author'))
  File "/Users/leonf/Develop/workspace/xxx/app/modules/admin/views.py", line 88, in __init__
    super(AuthorView, self).__init__(Author, session, **kwargs)
  File "/Users/leonf/Develop/workspace/xxx/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 329, in __init__
    menu_icon_value=menu_icon_value)
  File "/Users/leonf/Develop/workspace/xxx/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 782, in __init__
    self._refresh_cache()
  File "/Users/leonf/Develop/workspace/xxx/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 903, in _refresh_cache
    self._refresh_filters_cache()
  File "/Users/leonf/Develop/workspace/xxx/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 811, in _refresh_filters_cache
    self._filters = self.get_filters()
  File "/Users/leonf/Develop/workspace/xxx/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 1117, in get_filters
    raise Exception('Unsupported filter type %s' % n)
Exception: Unsupported filter type email
```


```
class Author(db.Model):
    ...
    email = db.Column(LowerCaseText, index=True)

class LowerCaseText(types.TypeDecorator):
    """Converts strings to lower case on the way in."""
    impl = types.Text

    def process_bind_param(self, value, dialect):
        return value.lower()
```

**Comment by killian-dunne** [comment]
Any progress here? This is a v common use case

**Comment by jrecasens** [comment]
no updates?
